language: ruby
rvm:
  - 1.9.2
  - 1.9.3
env:
  - CHEF_VERSION=0.9.18
  - CHEF_VERSION=0.10.8
  - CHEF_VERSION=10.12.0
gemfile:
  - test/support/Gemfile
script:
  - bundle exec rake knife
  - bundle exec rake tailor
  - bundle exec rake foodcritic